[package]
name = "pbgui-toolbar"
version = "0.1.0"
authors = ["jlgerber <jlgerber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qt_core = "0.4.1"
qt_gui = "0.4.1"
qt_widgets = "0.4.1"
qt_ui_tools = "0.4.1"
whoami = "0.7.0"
log = "0.4.8"
rustqt-utils = {git="https://github.com/jlgerber/rustqt-utils", tag="v0.1.0"}